#!/bin/bash  
#para correr -> ./run 

# 	rm client;  g++ -std=c++11 client.cpp include/*.cpp -I include/ -lssl -lcrypto -lpthread -o client; ./client
# 	rm client; g++ -std=c++11 client.cpp  include/*.cpp -I include/ -lpthread -lssl -lcrypto -I/usr/local/opt/openssl@1.1/include -L/usr/local/opt/openssl@1.1/lib -o client; ./client


rm App
#g++ -std=c++11 *.cpp -I/usr/local/opt/openssl@1.1/include -L/usr/local/opt/openssl@1.1/lib -o App
#g++ -std=c++11 *.cpp  -I/openssl-OpenSSL_1_1_1d/include/ -L/openssl-OpenSSL_1_1_1d  -o App

#g++ -std=c++11 *.cpp  openssl-OpenSSL_1_1_1d/include/openssl/*.h  -o App
#gcc App.c  -ldl  -lresolv -lsms -lssl -Wall  openssl-OpenSSL_1_1_1d/apps/openssl   -o App

gcc -m64 -I /openssl-OpenSSL_1_1_1d/include App.c -L/openssl-OpenSSL_1_1_1d/include -lcrypto -lssl

./App



